#!/bin/sh

if [ -f "/etc/init.d/check_update.sh" ]; then
  sh /etc/init.d/check_update.sh &
fi

if [ -d "/home/WebOnBoard" ]; then
  cd /home/WebOnBoard
  if [ -f "/home/WebOnBoard/auto_start.sh" ]; then
    sh auto_start.sh &
  fi
fi

#ntpdate 0.pool.ntp.org
#if [ "$?" == 0 ]
#then
#    hwclock -w
#else
#    reboot
#fi
