#!/bin/sh

MDEV=mmcblk0p1
if [[ -n $1 ]]; then
	MDEV=$1
fi

if [[ -f /media/$MDEV/update ]]; then

	rm -rf /media/$MDEV/update
	
	echo "Updating..."
	if [[ -f /media/$MDEV/rm.list ]]; then
		printf "Remove Files: "

		cat /media/$MDEV/rm.list | xargs rm -rf

		echo "OK"
	fi
	if [[ -d /media/$MDEV/rootfs ]]; then
		printf "Replace Root File System: "

		mkdir -p /root/tmp_rootfs
		cp -rf /media/$MDEV/rootfs/* /root/tmp_rootfs

		cd /root/tmp_rootfs

		chown -R root:root *
		find . -type d | xargs chmod -f 755
        find . -type f | xargs chmod -f 640
        chmod -f 750 etc/init.d/*
		chmod -f 750 opt/bin/*
		chmod -f 750 opt/sbin/*
		chmod -f 755 usr/local/bin/*
		chmod -f 755 usr/local/sbin/*

		cp -rf * /

		cd /root
		rm -rf tmp_rootfs

		echo "OK"
	fi

	if [[ -d /media/$MDEV/python_pkg ]]; then
		printf "Update Python Packages: "

		for file in `ls -a /media/$MDEV/python_pkg`
		do
			if [[ -f /media/$MDEV/python_pkg/$file ]]; then
				if [[ "${file##*.}"x = "gz"x ]]; then
					cd /media/$MDEV/python_pkg
					tar zxf $file
				fi
			fi
		done

		for file in `ls -a /media/$MDEV/python_pkg`
		do
			if [[ -d /media/$MDEV/python_pkg/$file ]]; then
				if [[ -f /media/$MDEV/python_pkg/$file/setup.py ]]; then
					cd /media/$MDEV/python_pkg/$file
					python setup.py install
				fi
			fi
		done

		echo "OK"
	fi

	if [[ -f /media/$MDEV/MLO ]]; then
		printf "Update MLO: "
		
		spl_mtdindex_line=`cat /proc/mtd | grep \"SPL\"`
        spl_mtdindex=${spl_mtdindex_line%%:*}

        spl_size_line=`mtd_debug info /dev/${spl_mtdindex} | grep mtd.size`
        spl_size_line_l=`echo ${spl_size_line%% (*}`
        spl_size=`echo ${spl_size_line_l#*= }`

        spl_erasesize_line=`mtd_debug info /dev/${spl_mtdindex} | grep mtd.erasesize`
        spl_erasesize_line_l=`echo ${spl_erasesize_line%% (*}`
        spl_erasesize=`echo ${spl_erasesize_line_l#*= }`

        spl_blockcnt=$[spl_size/spl_erasesize]

		flash_erase /dev/${spl_mtdindex} 0x0 ${spl_blockcnt}
		nandwrite -p /dev/${spl_mtdindex} /media/$MDEV/MLO

		echo "OK - "${spl_mtdindex}" blockcnt: "${spl_blockcnt}
	fi

	if [[ -f /media/$MDEV/u-boot.img ]]; then
		printf "Update u-boot.img: "

		uboot_mtdindex_line=`cat /proc/mtd | grep \"U-Boot\"`
		uboot_mtdindex=${uboot_mtdindex_line%%:*}

        uboot_size_line=`mtd_debug info /dev/${uboot_mtdindex} | grep mtd.size`
        uboot_size_line_l=`echo ${uboot_size_line%% (*}`
        uboot_size=`echo ${uboot_size_line_l#*= }`

        uboot_erasesize_line=`mtd_debug info /dev/${uboot_mtdindex} | grep mtd.erasesize`
        uboot_erasesize_line_l=`echo ${uboot_erasesize_line%% (*}`
        uboot_erasesize=`echo ${uboot_erasesize_line_l#*= }`

        uboot_blockcnt=$[uboot_size/uboot_erasesize]

		flash_erase /dev/${uboot_mtdindex} 0x0 ${uboot_blockcnt}
		nandwrite -p /dev/${uboot_mtdindex} /media/$MDEV/u-boot.img

		echo "OK - "${uboot_mtdindex}" blockcnt: "${uboot_blockcnt}
	fi
	
	if [[ -f /media/$MDEV/uImage ]]; then
		printf "Update uImage: "

		kernel_mtdindex_line=`cat /proc/mtd | grep \"Kernel\"`
		kernel_mtdindex=${kernel_mtdindex_line%%:*}

        kernel_size_line=`mtd_debug info /dev/${kernel_mtdindex} | grep mtd.size`
        kernel_size_line_l=`echo ${kernel_size_line%% (*}`
        kernel_size=`echo ${kernel_size_line_l#*= }`

        kernel_erasesize_line=`mtd_debug info /dev/${kernel_mtdindex} | grep mtd.erasesize`
        kernel_erasesize_line_l=`echo ${kernel_erasesize_line%% (*}`
        kernel_erasesize=`echo ${kernel_erasesize_line_l#*= }`

        kernel_blockcnt=$[kernel_size/kernel_erasesize]

		flash_erase /dev/${kernel_mtdindex} 0x0 ${kernel_blockcnt}
		nandwrite -p /dev/${kernel_mtdindex} /media/$MDEV/uImage

		echo "OK - "${kernel_mtdindex}" blockcnt: "${kernel_blockcnt}
	fi

	echo "Rebooting..."
	reboot
fi
