#!/bin/sh

case "$1" in
start)
    if [[ ! -f /etc/htbox/htbox.conf ]]; then
        echo -e "\nBox Reset..."

        /opt/bin/box_reset miss >/dev/null

        echo -e "\nBox Reset: OK"
    fi
    ;;
stop)
    echo ""
    ;;
*)
    echo "Usage: $0 {start} {stop}" >&2
    exit 1
    ;;
esac

exit 0
