port 1194
proto udp
dev tap
ca server/ca.crt
cert server/server.crt
key server/server.key
dh server/dh.pem
server-bridge 192.168.0.2 255.255.255.0 192.168.0.100 192.168.0.199
client-to-client
keepalive 10 120
tls-auth server/ta.key 0
cipher AES-256-CBC
persist-key
persist-tun
status server/openvpn-status.log 1
verb 3