#!/bin/sh

case "$1" in
start)
  if [ -f "/opt/bin/auto_start.sh" ]; then
    cd /opt/bin
    sh auto_start.sh &
  fi
  ;;
stop)
  ;;
*)
  echo "Usage: $0 {start} {stop}" >&2
  exit 1
  ;;
esac

exit 0
