#!/bin/sh

case "$1" in
start)
	if [[ -f /etc/sysreset ]]; then
		rm -rf /etc/sysreset
		echo -ne "\n\n[===SYS RESET]: "

		/opt/sbin/sys_reset

		echo -e "OK\n"
	fi
	;;
stop)
	echo ""
	;;
*)
	echo "Usage: $0 {start} {stop}" >&2
	exit 1
	;;
esac

exit 0
