#!/bin/sh

case "$1" in
start)
	if [[ -f /etc/sysreset ]]; then
		rm -rf /etc/sysreset
		printf "系统初始化: "
		/opt/sbin/sys_reset
		echo "OK"
	fi
	;;
*)
	echo "Usage: $0 {start}" >&2
	exit 1
	;;
esac

exit 0
