#!/bin/sh

case "$1" in
start)
	echo -ne "\n\n[======SYS BT]: "

	bluetoothd
	hciconfig hci0 up
	sdptool add SP

	echo -e "OK\n"
	;;
stop)
	echo ""
	;;
*)
	echo "Usage: $0 {start} {stop}" >&2
	exit 1
	;;
esac

exit 0
