#!/bin/sh

s_line=`cat /proc/cpuinfo | grep Serial`
s=`echo ${s_line#*": "}`
s4=${s:0-4}

sed -i "1c htbox-${s4}" /etc/hostname
sed -i "2c 127.0.1.1	htbox-${s4}" /etc/hosts
sed -i "9c Name = htbox-${s4}" /etc/bluetooth/main.conf
