name: A Test CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  job_prepare:
    name: Job - Prepare
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Dir and File
        run: |
          mkdir -p upload_artifact/publish
          touch upload_artifact/publish/testfile.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./upload_artifact

  job_github_release:
    name: Job Github Release
    needs: [job_prepare]
    runs-on: ubuntu-18.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ./download_artifact/

      - name: Fix Package
        run: |
          zip -qr publish.zip publish
        working-directory: ./download_artifact

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tmp_tag
          release_name: Release tmp_tag
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./download_artifact/publish.zip
          asset_name: publish.zip
          asset_content_type: application/zip

  job_notification:
    name: Job Notification
    needs: [job_github_release]
    runs-on: ubuntu-18.04
    steps:
      - name: Get WECHATWORK ACCESS TOKEN
        id: get_token
        run: |
          RTN_gettoken=`curl --location --request GET "https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=${{ secrets.WECHATWORK_CORPID }}&corpsecret=${{ secrets.WECHATWORK_APP_CORPSECRET }}"`
          access_token=`echo ${RTN_gettoken} | jq -r '.access_token'`
          echo "ACCESS_TOKEN=${access_token}" >> $GITHUB_ENV

          echo "::set-output name=status::success"

      - name: Notification
        if: steps.get_token.outputs.status == 'success'
        run: |
          curl --location --request POST "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${ACCESS_TOKEN}" \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "touser" : "@all",
            "msgtype" : "textcard",
            "agentid" : '"${{ secrets.WECHATWORK_APP_AGENTID }}"',
            "textcard" : {
              "title" : "Github Action 生成固件",
              "description" : "<div class=\"gray\">'"$(date "+%Y年%m月%d日 %H:%M:%S")"'</div><div class=\"normal\">固件生成</div><div class=\"highlight\">请及时查看</div>",
              "url" : "https://m.baidu.com"
            }
          }'
          
