
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    
    steps:
    
      - name: STEP
        run: |
          cat /etc/resolv.conf
          ping 8.8.8.8 -c 3
