
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    
    steps:

      - name: Wget Toolchain
        run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Untar Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Wget Snap7
        run: wget https://netix.dl.sourceforge.net/project/snap7/Snap7-IoT/snap7-iot-arm/snap7-iot-arm-1.4.2.tar.gz

      - name: Untar Snap7
        run: tar zxvf snap7-iot-arm-1.4.2.tar.gz

      - name: Fix Snap7
        run: |
          sed -i '8c LinkerName := ${CROSS_COMPILE}g++' common.mk
          sed -i '9c SharedObjectLinkerName := ${CROSS_COMPILE}g++ -shared -fPIC' common.mk
          sed -i '30c AR := ${CROSS_COMPILE}ar rcus' common.mk
          sed -i '31c CXX := ${CROSS_COMPILE}g++' common.mk
          sed -i '32c CC := ${CROSS_COMPILE}gcc' common.mk
        working-directory: ./snap7-iot-arm-1.4.2/build/unix

      - name: Build Snap7
        env:
          TOOLCHAIN: /home/runner/work/actions-demo/actions-demo/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin
          CROSS_COMPILE: arm-linux-gnueabihf-
        run: |
          export PATH=$TOOLCHAIN:$PATH
          make -f arm_v7_linux.mk
          cp -f ../bin/arm_v7-linux/libsnap7.so /usr/lib
        working-directory: ./snap7-iot-arm-1.4.2/build/unix

      - name: Tar Snap7
        run: sudo tar zcf snap7.tar.gz /usr/lib/libsnap7.so
        working-directory: /

      - name: Upload Snap7
        uses: actions/upload-artifact@v2
        with:
          name: snap7.tar.gz
          path: /snap7.tar.gz
