name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  job_build:
    name: Job Build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Pull Kernel
      run: git clone https://github.com/cookie-dragon/forlinx-335xS-II-kernel.git kernel
      
    - name: Get Buildroot
      run: |
        wget https://buildroot.org/downloads/buildroot-2016.02.tar.gz
        tar zxvf buildroot-2016.02.tar.gz
        cp config.2016.02 buildroot-2016.02/.config
        
    - name: Build Toolchain
      run: |
        cd buildroot-2016.02
        make -j$(nproc)

    - name: Build Kernel
      env: 
        CROSS_COMPILE: arm-buildroot-linux-gnueabihf-
      run: |
        export PATH=/home/runner/work/actions-demo/actions-demo/host_2016.02/usr/bin:$PATH
        cd kernel
        make distclean ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
        make ok335xs2_evm_linux_defconfig ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
        make -j$(nproc) ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
        make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE uImage
        
    - name: UPload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: kernel/arch/arm/boot/uImage
      
    - name: Show
      run: |
        pwd
        ls -l
        cd kernel/arch/arm/boot
        ls -l
