name: C/C++ CI

on:
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]
  workflow_dispatch:

jobs:

  job_prepare:
    name: Job Prepare
    runs-on: ubuntu-18.04
    steps:

      # - name: APT
      #   run: |
      #     sudo apt-get update
      #     sudo dpkg --add-architecture i386
      #     sudo apt-get update
      #     sudo apt-get install -y git build-essential python diffstat texinfo gawk chrpath dos2unix wget unzip socat doxygen libc6:i386 libncurses5:i386 libstdc++6:i386 libz1:i386
      #     sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev
    
      - name: ECHO
        run: echo "Job Prepare"

  job_toolchain:
    name: Job Toolchain
    needs: [job_prepare]
    runs-on: ubuntu-18.04
    steps:

      # - name: SETP0 - Checkout
      #   uses: actions/checkout@v2

      # - name: Get Buildroot
      #   run: |
      #     wget https://buildroot.org/downloads/buildroot-2016.02.tar.gz
      #     tar zxf buildroot-2016.02.tar.gz
      #     cp -f buildroot-config/config.2016.02 buildroot-2016.02/.config
          
      # - name: Build Toolchain
      #   run: make -j$(nproc)
      #   working-directory: ./buildroot-2016.02

      - name: SETP1 - Get Toolchain
        run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: SETP2 - Upload Toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain
          path: gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

  job_kernel:
    name: Job Kernel
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:
    
      - name: SETP0 - Checkout
        uses: actions/checkout@v2

      - name: SETP1 - Download Toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./

      - name: SETP2 - Unzip Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: SETP3 - Pull Kernel
        run: git clone https://github.com/cookie-dragon/forlinx-335xS-II-kernel.git kernel
        
      - name: SETP4 - Change Kernel
        run: cp -rf htbox-kernel-add/* kernel/

      - name: SETP5 - Patch Kernel
        run : patch -p1 < ../timeconst.pl.x64.patch
        working-directory: ./kernel

      - name: SETP6 - Build Kernel
        env:
          TOOLCHAIN: /home/runner/work/actions-demo/actions-demo/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin
          CROSS_COMPILE: arm-linux-gnueabihf-
        run: |
          sudo apt-get update
          sudo apt-get install -y u-boot-tools
          export PATH=$TOOLCHAIN:$PATH
          make distclean ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make ok335xhtbox_evm_linux_defconfig ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make -j$(nproc) ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE uImage
        working-directory: ./kernel
          
      - name: SETP7 - Upload Kernel
        uses: actions/upload-artifact@v2
        with:
          name: uImage
          path: kernel/arch/arm/boot/uImage

  job_rootfs:
    name: Job Root File System
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:
    
      - name: SETP0 - Checkout
        uses: actions/checkout@v2

      - name: SETP1 - Download Toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./

      - name: SETP2 - Unzip Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: SETP3 - Download and Unzip Buildroot
        run: |
          wget https://buildroot.org/downloads/buildroot-2019.02.11.tar.gz
          tar zxf buildroot-2019.02.11.tar.gz
          wget https://buildroot.org/downloads/buildroot-2017.02.11.tar.gz
          tar zxf buildroot-2017.02.11.tar.gz
          wget https://buildroot.org/downloads/buildroot-2016.02.tar.gz
          tar zxf buildroot-2016.02.tar.gz

      - name: SETP4 - Fix Buildroot
        run: |
          rm -rf buildroot-2019.02.11/package/openssh
          cp -rf buildroot-2016.02/package/openssh buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/openssl
          cp -rf buildroot-2016.02/package/openssl buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/zlib
          cp -rf buildroot-2016.02/package/zlib buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/mosquitto
          cp -rf buildroot-2016.02/package/mosquitto buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/iproute2
          cp -rf buildroot-2017.02.11/package/iproute2 buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/paho-mqtt-c
          cp -rf buildroot-2017.02.11/package/paho-mqtt-c buildroot-2019.02.11/package/

      - name: SETP5 - Config Buildroot
        run: cp -f buildroot-config/config.base.2019.02.11 buildroot-2019.02.11/.config

      - name: SETP6 - Build Root File System
        run: make -j$(nproc)
        working-directory: ./buildroot-2019.02.11

      - name: SETP5 - Config BusyBox
        run: cp -f buildroot-config/config.1.29.3 buildroot-2019.02.11/output/build/busybox-1.29.3/.config

      - name: SETP6 - Build Root File System Again
        run: make -j$(nproc)
        working-directory: ./buildroot-2019.02.11

      - name: STEP7 - Upload Base Root File System
        uses: actions/upload-artifact@v2
        with:
          name: rootfs.tar
          path: buildroot-2019.02.11/output/images/rootfs.tar

      - name: STEP8 - Fix Root File System
        run: |
          mkdir -p rootfs
          tar xf buildroot-2019.02.11/output/images/rootfs.tar ./rootfs/

      - name: STEP9 - Build UBI File System
        run: |
          sudo apt-get update
          sudo apt-get install -y mtd-utils
          mkfs.ubifs -F -r rootfs -m 2048 -e 126976 -c 1866 -o ubifs.img
          ubinize -o ubi.img -m 2048 -p 128KiB -s 2048 -O 2048 ubinize-256M.cfg

      - name: STEP10 - Upload UBI File System
        uses: actions/upload-artifact@v2
        with:
          name: ubi.img
          path: ./ubi.img
