name: C/C++ CI

on:
  push:
    paths: 
      - 'htbox-kernel-add/**'
      - 'htbox-rootfs-add/**'
      - 'buildroot-config/**'
      - 'buildroot-patch/**'
  workflow_dispatch:

jobs:

  job_toolchain:
    name: Toolchain
    runs-on: ubuntu-18.04
    steps:
      
      # - name: Install Basic APT Packages
      #   run: |
      #     sudo dpkg --add-architecture i386
      #     sudo apt-get update
      #     sudo apt-get -y install git build-essential python diffstat texinfo gawk chrpath dos2unix wget unzip socat doxygen libc6:i386 libncurses5:i386 libstdc++6:i386 libz1:i386
      #     sudo apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev

      # - name: Install APT Packages
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y u-boot-tools mtd-utils

      - name: Wget Toolchain
        run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Upload Artifact Toolchain
        uses: actions/upload-artifact@v2
        with:
          name: gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
          path: ./gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

  job_base_rootfs:
    name: Base Root File System
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifact Toolchain
        uses: actions/download-artifact@v2
        with:
          name: gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
          path: ./

      - name: Untar Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Wget Buildroot
        run: |
          wget https://buildroot.org/downloads/buildroot-2019.02.11.tar.gz
          wget https://buildroot.org/downloads/buildroot-2017.02.11.tar.gz
          wget https://buildroot.org/downloads/buildroot-2016.02.tar.gz

      - name: Untar Buildroot
        run: |
          tar zxf buildroot-2019.02.11.tar.gz
          tar zxf buildroot-2017.02.11.tar.gz
          tar zxf buildroot-2016.02.tar.gz

      - name: Replace Buildroot Package Version
        run: |
          rm -rf buildroot-2019.02.11/package/openssh
          cp -rf buildroot-2016.02/package/openssh buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/openssl
          cp -rf buildroot-2016.02/package/openssl buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/zlib
          cp -rf buildroot-2016.02/package/zlib buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/mosquitto
          cp -rf buildroot-2016.02/package/mosquitto buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/iproute2
          cp -rf buildroot-2017.02.11/package/iproute2 buildroot-2019.02.11/package/
          rm -rf buildroot-2019.02.11/package/paho-mqtt-c
          cp -rf buildroot-2017.02.11/package/paho-mqtt-c buildroot-2019.02.11/package/

      - name: Patch Buildroot Package
        run: |
          patch -p1 < ../buildroot-patch/ncurses.mk.patch
        working-directory: ./buildroot-2019.02.11

      - name: Config Buildroot
        run: cp -f buildroot-config/config.base.2019.02.11 buildroot-2019.02.11/.config

      - name: Build Buildroot
        run: make -j$(nproc)
        working-directory: ./buildroot-2019.02.11

      - name: Config BusyBox
        run: cp -f buildroot-config/config.1.29.3 buildroot-2019.02.11/output/build/busybox-1.29.3/.config

      - name: Build Buildroot Again
        run: make -j$(nproc)
        working-directory: ./buildroot-2019.02.11

      - name: Upload Artifact Base Root File System
        uses: actions/upload-artifact@v2
        with:
          name: rootfs.tar
          path: ./buildroot-2019.02.11/output/images/rootfs.tar

  job_kernel:
    name: Kernel
    needs: [job_toolchain, job_base_rootfs]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install APT Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y u-boot-tools

      - name: Download Artifact Toolchain
        uses: actions/download-artifact@v2
        with:
          name: gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
          path: ./

      - name: Untar Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Git Kernel
        run: git clone https://github.com/cookie-dragon/forlinx-335xS-II-kernel.git kernel

      - name: Patch Kernel
        run : patch -p1 < ../timeconst.pl.x64.patch
        working-directory: ./kernel

      - name: Add Kernel File
        run: cp -rf htbox-kernel-add/* kernel/

      - name: Build Kernel
        env:
          TOOLCHAIN: /home/runner/work/actions-demo/actions-demo/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin
          CROSS_COMPILE: arm-linux-gnueabihf-
        run: |
          export PATH=$TOOLCHAIN:$PATH
          make distclean ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make ok335xhtbox_evm_linux_defconfig ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make -j$(nproc) ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE uImage
          make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules
        working-directory: ./kernel

      - name: Upload Artifact Kernel
        uses: actions/upload-artifact@v2
        with:
          name: uImage
          path: ./kernel/arch/arm/boot/uImage

      - name: Download Artifact Base Root File System
        uses: actions/download-artifact@v2
        with:
          name: rootfs.tar
          path: ./

      - name: Untar Base Root File System
        run: |
          mkdir -p rootfs
          tar xf rootfs.tar -C ./rootfs/
          
      - name: Kernel Modules Install
        env:
          TOOLCHAIN: /home/runner/work/actions-demo/actions-demo/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin
          CROSS_COMPILE: arm-linux-gnueabihf-
        run: make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules_install INSTALL_MOD_PATH=../rootfs/
        working-directory: ./kernel

      - name: Tar Root File System
        run: |
          mkdir -p rootfs
          tar zxf rootfs.tar.gz rootfs/

      - name: Upload Root File System
        uses: actions/upload-artifact@v2
        with:
          name: rootfs.tar.gz
          path: ./rootfs.tar.gz

  job_final_rootfs:
    name: Final Root File System
    needs: [job_kernel]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install APT Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y mtd-utils

      - name: Download Artifact Root File System
        uses: actions/download-artifact@v2
        with:
          name: rootfs.tar.gz
          path: ./

      - name: Untar Base Root File System
        run: tar zxf rootfs.tar.gz

      - name: ROOTFS - Fix Root File System
        run: |
          rm -rf rootfs/lib/modules/3.2.0/source
          rm -rf rootfs/etc/init.d/S60openvpn
          cp -rf htbox-rootfs-add/* rootfs/
          chmod +x rootfs/etc/init.d/*
          chmod +x rootfs/usr/local/bin/*

      - name: Build UBI File System
        run: |
          mkfs.ubifs -F -r rootfs -m 2048 -e 126976 -c 1866 -o ubifs.img
          ubinize -o ubi.img -m 2048 -p 128KiB -s 2048 -O 2048 ubinize-256M.cfg

      - name: Upload Artifact UBI File System
        uses: actions/upload-artifact@v2
        with:
          name: ubi.img
          path: ./ubi.img
