name: common CI

on:
  # push:
  #   paths: 
  #     - 'common/**'
  #     - '.github/workflows/common.yml'
  workflow_dispatch:

jobs:
  job_test:
    name: Job - Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step - Test
        run: |
          mkdir -p rootfs

          sudo chown -R root:root htbox-forlinx/rootfs-add/*
          sudo find ./htbox-forlinx/rootfs-add -type d | xargs sudo chmod 777
          sudo find ./htbox-forlinx/rootfs-add -type f | xargs sudo chmod 640
          
          sudo chmod -R 750 htbox-forlinx/rootfs-add/etc/init.d/*
          sudo chmod -R 750 htbox-forlinx/rootfs-add/etc/mdev/*
          sudo chmod -R 440 htbox-forlinx/rootfs-add/etc/sudoers.d/*
          sudo chmod -R 750 htbox-forlinx/rootfs-add/opt/sbin/*
          sudo chmod -R 755 htbox-forlinx/rootfs-add/usr/local/bin/*

          sudo cp -rf htbox-forlinx/rootfs-add/* rootfs/
