name: common CI

on:
  push:
    paths: 
      - 'common/**'
      - '.github/workflows/common.yml'
  workflow_dispatch:

jobs:
  
  # job_toolchain:
  #   name: Toolchain
  #   runs-on: ubuntu-18.04
  #   steps:

  #     # - name: Install Basic APT Packages
  #     #   run: |
  #     #     sudo dpkg --add-architecture i386
  #     #     sudo apt-get update
  #     #     sudo apt-get -y install git build-essential python diffstat texinfo gawk chrpath dos2unix wget unzip socat doxygen libc6:i386 libncurses5:i386 libstdc++6:i386 libz1:i386
  #     #     sudo apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev

  #     # - name: Install APT Packages
  #     #   run: |
  #     #     sudo apt-get update
  #     #     sudo apt-get install -y u-boot-tools mtd-utils

  #     - name: Wget Toolchain
  #       run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

  #     - name: Upload Artifact Toolchain
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
  #         path: ./gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

  job_env:
    name: JOB Env
    runs-on: ubuntu-18.04
    outputs:
      S_FILENAME: ${{steps.step2.outputs.S_FILENAME}}
      U_FILENAME: ${{steps.step2.outputs.U_FILENAME}}
      K_FILENAME: ${{steps.step2.outputs.K_FILENAME}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: step1
        name: Check Versions
        run: |
          KERNEL_VERSION=`cat hilectroElec/version.json | jq -r '.kernel_version'`
          FILE_SYS_VERSION=`cat hilectroElec/version.json | jq -r '.FILE_SYS_VERSION'`
          DATE_VERSION=`cat hilectroElec/version.json | jq -r '.date_version'`
          SCREEN_RESOLUTION=`cat hilectroElec/version.json | jq -r '.screen_resolution'`
          echo ${KERNEL_VERSION} ${FILE_SYS_VERSION} ${DATE_VERSION} ${SCREEN_RESOLUTION}
          echo "::set-output name=KERNEL_VERSION::${KERNEL_VERSION}"
          echo "::set-output name=FILE_SYS_VERSION::${FILE_SYS_VERSION}"
          echo "::set-output name=DATE_VERSION::${DATE_VERSION}"
          echo "::set-output name=SCREEN_RESOLUTION::${SCREEN_RESOLUTION}"

      - id: step2
        name: Check Output File Name
        run: |
          S_FILENAME=T2-Kernel-V${{steps.step1.outputs.KERNEL_VERSION}}-Filesys-V${{steps.step1.outputs.FILE_SYS_VERSION}}-S-${{steps.step1.outputs.DATE_VERSION}}
          U_FILENAME=T2-Kernel-V${{steps.step1.outputs.KERNEL_VERSION}}-Filesys-V${{steps.step1.outputs.FILE_SYS_VERSION}}-U-${{steps.step1.outputs.DATE_VERSION}}
          K_FILENAME=kernel_${{steps.step1.outputs.SCREEN_RESOLUTION}}_${{steps.step1.outputs.DATE_VERSION}}
          echo ${S_FILENAME} ${U_FILENAME} ${K_FILENAME}
          echo "::set-output name=S_FILENAME::${S_FILENAME}"
          echo "::set-output name=U_FILENAME::${U_FILENAME}"
          echo "::set-output name=K_FILENAME::${K_FILENAME}"

  job_file:
    name: JOB File
    runs-on: ubuntu-18.04
    needs: [job_env]
    steps:

      - name: Prepare Dir
        run: |
          mkdir -p ${{needs.job_env.outputs.S_FILENAME}}
          sudo mkdir -p /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}

      - name: Prepare File
        run: |
          touch ${{needs.job_env.outputs.S_FILENAME}}/MLO
          touch ${{needs.job_env.outputs.S_FILENAME}}/u-boot.img
          touch ${{needs.job_env.outputs.S_FILENAME}}/uImage
          touch ${{needs.job_env.outputs.S_FILENAME}}/ubi.img
          sudo cp -f ${{needs.job_env.outputs.S_FILENAME}}/MLO /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}
          sudo cp -f ${{needs.job_env.outputs.S_FILENAME}}/u-boot.img /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}
          sudo cp -f ${{needs.job_env.outputs.S_FILENAME}}/uImage /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}

      - name: Zip S
        run: zip -q -r ${{needs.job_env.outputs.S_FILENAME}}.zip ${{needs.job_env.outputs.S_FILENAME}}

      - name: Upload S
        uses: actions/upload-artifact@v2
        with:
          name: ${{needs.job_env.outputs.S_FILENAME}}.zip
          path: ./${{needs.job_env.outputs.S_FILENAME}}.zip

      - name: Check MD5
        run: |
          DIR=/home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}
          sudo md5sum ${DIR}/MLO > ${DIR}/uplicence.txt
          sudo md5sum ${DIR}/u-boot.img >> ${DIR}/uplicence.txt
          sudo md5sum ${DIR}/uImage >> ${DIR}/uplicence.txt

      - name: Zip U
        run: zip -q -r $${{needs.job_env.outputs.U_FILENAME}}.zip ${{needs.job_env.outputs.K_FILENAME}}
        working-directory: /home/haitian/onekey_update

      - name: Upload U
        uses: actions/upload-artifact@v2
        with:
          name: ${{needs.job_env.outputs.U_FILENAME}}.zip
          path: /home/haitian/onekey_update/${{needs.job_env.outputs.U_FILENAME}}.zip

      - name: STEP - TEST
        run: |
          DIR=/home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}
          sudo cat ${DIR}/uplicence.txt
          sudo ls -l ${DIR}
