name: hilectroElec CI

on:
  # push:
  #   paths: 
  #     - 'common/**'
  #     - 'hilectroElec/version.json'
  #     - 'hilectroElec/**'
  #     - '.github/workflows/hilectroElec.yml'
  workflow_dispatch:
    inputs:
      cross_compile:
        description: 'PREFIX'
        required: true
        default: 'arm-linux-gnueabihf'
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:

  job_env:
    name: ENV
    runs-on: ubuntu-18.04
    outputs:
      KERNEL_VERSION: ${{steps.step_set_version.outputs.KERNEL_VERSION}}
      FILE_SYS_VERSION: ${{steps.step_set_version.outputs.FILE_SYS_VERSION}}
      DATE_VERSION: ${{steps.step_set_version.outputs.DATE_VERSION}}
      SCREEN_RESOLUTION: ${{steps.step_set_version.outputs.SCREEN_RESOLUTION}}
      S_FILENAME: ${{steps.step_set_filename.outputs.S_FILENAME}}
      U_FILENAME: ${{steps.step_set_filename.outputs.U_FILENAME}}
      K_FILENAME: ${{steps.step_set_filename.outputs.K_FILENAME}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: step_set_version
        name: Set Version
        run: |
          KERNEL_VERSION=`cat hilectroElec/version.json | jq -r '.kernel_version'`
          FILE_SYS_VERSION=`cat hilectroElec/version.json | jq -r '.FILE_SYS_VERSION'`
          DATE_VERSION=`cat hilectroElec/version.json | jq -r '.date_version'`
          SCREEN_RESOLUTION=`cat hilectroElec/version.json | jq -r '.screen_resolution'`

          echo ${KERNEL_VERSION} ${FILE_SYS_VERSION} ${DATE_VERSION} ${SCREEN_RESOLUTION}

          echo "::set-output name=KERNEL_VERSION::${KERNEL_VERSION}"
          echo "::set-output name=FILE_SYS_VERSION::${FILE_SYS_VERSION}"
          echo "::set-output name=DATE_VERSION::${DATE_VERSION}"
          echo "::set-output name=SCREEN_RESOLUTION::${SCREEN_RESOLUTION}"

      - id: step_set_filename
        name: Set Filename
        run: |
          S_FILENAME=T2-Kernel-V${{steps.step_set_version.outputs.KERNEL_VERSION}}-Filesys-V${{steps.step_set_version.outputs.FILE_SYS_VERSION}}-S-${{steps.step_set_version.outputs.DATE_VERSION}}
          U_FILENAME=T2-Kernel-V${{steps.step_set_version.outputs.KERNEL_VERSION}}-Filesys-V${{steps.step_set_version.outputs.FILE_SYS_VERSION}}-U-${{steps.step_set_version.outputs.DATE_VERSION}}
          K_FILENAME=kernel_${{steps.step_set_version.outputs.SCREEN_RESOLUTION}}_${{steps.step_set_version.outputs.DATE_VERSION}}

          echo ${S_FILENAME} ${U_FILENAME} ${K_FILENAME}

          echo "::set-output name=S_FILENAME::${S_FILENAME}"
          echo "::set-output name=U_FILENAME::${U_FILENAME}"
          echo "::set-output name=K_FILENAME::${K_FILENAME}"

  job_toolchain:
    name: Toolchain
    runs-on: ubuntu-18.04
    outputs:
      TOOLCHAIN: ${{steps.step_set_toolchain.outputs.TOOLCHAIN}}
      PREFIX: ${{steps.step_set_prefix_cross_compile.outputs.PREFIX}}
      CROSS_COMPILE: ${{steps.step_set_prefix_cross_compile.outputs.CROSS_COMPILE}}
    steps:
      
      - name: Wget Toolchain
        run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Untar Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
      
      - name: Rename Toolchain
        run: mv gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux toolchain
        
      - id: step_set_toolchain
        name: Set TOOLCHAIN
        run: |
          TOOLCHAIN=`pwd`
          echo "::set-output name=TOOLCHAIN::${TOOLCHAIN}"
        working-directory: ./toolchain
        
      - id: step_set_prefix_cross_compile
        name: Set PREFIX and CROSS_COMPILE
        run: |
          if [ -z "${{github.event.inputs.cross_compile}}" ]; then
            PREFIX=arm-linux-gnueabihf
          else
            PREFIX=${{github.event.inputs.cross_compile}}
          fi
          echo "::set-output name=PREFIX::${PREFIX}"
          CROSS_COMPILE=${PREFIX}-
          echo "::set-output name=CROSS_COMPILE::${CROSS_COMPILE}"

      - name: Retar Toolchain
        run: tar zcf toolchain.tar.gz toolchain

      - name: Upload Artifact toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain
          path: ./toolchain.tar.gz

  job_rootfs_forlinx:
    name: Forlinx Root File System
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Official Root File System
        run: git clone -b 20200803 https://github.com/cookie-dragon/forlinx-335xS-II-rootfs.git

      - name: Untar Official Root File System
        run: |
          mkdir -p rootfs
          sudo tar xf forlinx-335xS-II-rootfs/qt/rootfs.tar.bz2 -C ./rootfs/

      - name: Fix Root File System
        run: |
          sudo rm -rf rootfs/forlinx/audio/
          sudo rm -rf rootfs/forlinx/bin/
          sudo rm -rf rootfs/forlinx/video/
          sudo rm -rf rootfs/forlinx/web/
          sudo rm -rf rootfs/forlinx/qt/bin/*

      - name: Tar Base Root File System
        run: sudo tar cf rootfs.tar * 
        working-directory: ./rootfs

      - name: Upload Artifact rootfs_forlinx
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_forlinx
          path: ./rootfs/rootfs.tar

  job_kernel:
    name: Kernel
    needs: [job_env, job_toolchain, job_rootfs_forlinx]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install APT Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y u-boot-tools

      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./

      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz

      - name: Get Kernel
        run: git clone -b 20200803 https://github.com/cookie-dragon/forlinx-335xS-II-kernel.git kernel

      - name: Add Kernel File
        run: cp -rf hilectroElec/kernel-add/* kernel/

      - name: Config Kernel
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make distclean ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make ok335xs2_evm_linux_defconfig ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
        working-directory: ./kernel

      - name: Patch Kernel
        run : |
          patch -p1 < ../common/kernel-patch/timeconst.pl.x64.patch
          patch -p2 < ../hilectroElec/kernel-patch/diff.patch
        working-directory: ./kernel

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Fix version
        run: echo "Fix version"

      - name: Build Kernel
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make -j$(nproc) ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE uImage
          make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules
        working-directory: ./kernel

      - name: Upload Artifact uImage
        uses: actions/upload-artifact@v2
        with:
          name: uImage
          path: ./kernel/arch/arm/boot/uImage

      - name: Download Artifact rootfs_forlinx
        uses: actions/download-artifact@v2
        with:
          name: rootfs_forlinx
          path: ./

      - name: Untar Buildroot Root File System
        run: |
          mkdir -p rootfs
          sudo tar xf rootfs.tar -C ./rootfs/
          
      - name: Kernel Modules Install
        env:
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: sudo make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules_install INSTALL_MOD_PATH=../rootfs/
        working-directory: ./kernel

      - name: Tar Buildroot Root File System With Modules
        run: sudo tar zcf rootfs.tar.gz rootfs/

      - name: Upload Artifact rootfs_forlinx_with_modules
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_forlinx_with_modules
          path: ./rootfs.tar.gz

  job_rootfs_part_business:
    name: Job - Rootfs Part - Business
    needs: [job_env]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Rootfs Dir
        run: |
          sudo mkdir -p rootfs
          sudo cp -rf hilectroElec/rootfs-add/* rootfs/
          sudo chown -R root:root rootfs

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Fix version
        run: echo "Fix version"

      - name: Fix
        run: |
          sudo find . -type d | xargs sudo chmod 755
          sudo find . -type f | xargs sudo chmod 640

          sudo chmod 755 etc/init.d/*
          sudo chmod 755 etc/rc5.d/*
          sudo chmod 755 home/haitian/tpboard/tpView

          tree -pug
        working-directory: ./rootfs

      - name: Tar
        run: sudo tar zcf rootfs_part_business.tgz rootfs/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_part_business
          path: ./rootfs_part_business.tgz

  job_final_rootfs:
    name: Final Root File System
    needs: [job_kernel, job_rootfs_part_business]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install APT Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y mtd-utils

      - name: Download Artifact rootfs_forlinx_with_modules
        uses: actions/download-artifact@v2
        with:
          name: rootfs_forlinx_with_modules
          path: ./

      - name: Untar Root File System
        run: sudo tar zxf rootfs.tar.gz

      # ########## # ########## # ########## # ########## # ########## #

      - name: Fix Root File System (Base)
        run: |
          sudo rm -rf rootfs/lib/modules/*/build
          sudo rm -rf rootfs/lib/modules/*/source

      - name: Download Artifact rootfs_part_business
        uses: actions/download-artifact@v2
        with:
          name: rootfs_part_business
          path: ./

      - name: Untar rootfs_part_business
        run: sudo tar zxf rootfs_part_business.tgz

      - name: Tar Final Root File System (Business)
        run: sudo tar zcf rootfs_final_business.tar.gz rootfs/

      - name: Upload Artifact rootfs_final_business (Business)
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_final_business
          path: ./rootfs_final_business.tar.gz

      - name: Build UBI File System (Business)
        run: |
          sudo mkfs.ubifs -F -r rootfs -m 2048 -e 126976 -c 1866 -o ubifs.img
          sudo ubinize -o ubi.img -m 2048 -p 128KiB -s 2048 -O 2048 hilectroElec/rootfs-config/ubinize-256M.cfg

      - name: Upload Artifact ubi_business (Business)
        uses: actions/upload-artifact@v2
        with:
          name: ubi_business
          path: ./ubi.img

  job_final_package:
    name: Final Package
    needs: [job_env, job_kernel, job_final_rootfs]
    runs-on: ubuntu-18.04
    steps:

      - name: Download Artifact uImage
        uses: actions/download-artifact@v2
        with:
          name: uImage
          path: ./

      - name: Download Artifact ubi_business (Business)
        uses: actions/download-artifact@v2
        with:
          name: ubi_business
          path: ./

      - name: Prepare Dir
        run: |
          mkdir -p output/${{needs.job_env.outputs.S_FILENAME}}
          sudo mkdir -p /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}

      - name: Prepare File
        run: |
          git clone -b 20161008 https://github.com/cookie-dragon/forlinx-335xS-II-uboot.git

          cp forlinx-335xS-II-uboot/256M/MLO output/${{needs.job_env.outputs.S_FILENAME}}/
          cp forlinx-335xS-II-uboot/256M/u-boot.img output/${{needs.job_env.outputs.S_FILENAME}}/
          cp uImage output/${{needs.job_env.outputs.S_FILENAME}}
          cp ubi.img output/${{needs.job_env.outputs.S_FILENAME}}

          sudo cp -f output/${{needs.job_env.outputs.S_FILENAME}}/MLO /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}/
          sudo cp -f output/${{needs.job_env.outputs.S_FILENAME}}/u-boot.img /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}/
          sudo cp -f output/${{needs.job_env.outputs.S_FILENAME}}/uImage /home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}/

      - name: Upload S
        uses: actions/upload-artifact@v2
        with:
          name: ${{needs.job_env.outputs.S_FILENAME}}
          path: ./output

      - name: Check MD5
        run: |
          DIR=/home/haitian/onekey_update/${{needs.job_env.outputs.K_FILENAME}}
          sudo md5sum ${DIR}/MLO > ${DIR}/uplicence.txt
          sudo md5sum ${DIR}/u-boot.img >> ${DIR}/uplicence.txt
          sudo md5sum ${DIR}/uImage >> ${DIR}/uplicence.txt

          sudo cat ${DIR}/uplicence.txt

      - name: Upload U
        uses: actions/upload-artifact@v2
        with:
          name: ${{needs.job_env.outputs.U_FILENAME}}
          path: /home/haitian/onekey_update
