name: htbox-forlinx2 CI

on:
  push:
    paths: 
      # - 'common/**'
      # - 'htbox-forlinx/version.json'
      # - 'htbox-forlinx/**'
      - '.github/workflows/htbox-forlinx2.yml'
  workflow_dispatch:
    inputs:
      cross_compile:
        description: 'PREFIX'
        required: true
        default: 'arm-linux-gnueabihf'

jobs:

  job_toolchain:
    name: Toolchain
    runs-on: ubuntu-18.04
    outputs:
      TOOLCHAIN: ${{steps.step_set_toolchain.outputs.TOOLCHAIN}}
      PREFIX: ${{steps.step_set_prefix_cross_compile.outputs.PREFIX}}
      CROSS_COMPILE: ${{steps.step_set_prefix_cross_compile.outputs.CROSS_COMPILE}}
    steps:
      
      - name: Wget Toolchain
        run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Untar Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
      
      - name: Rename Toolchain
        run: mv gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux toolchain
        
      - id: step_set_toolchain
        name: Set TOOLCHAIN
        run: |
          TOOLCHAIN=`pwd`
          echo "::set-output name=TOOLCHAIN::${TOOLCHAIN}"
        working-directory: ./toolchain
        
      - id: step_set_prefix_cross_compile
        name: Set PREFIX and CROSS_COMPILE
        run: |
          if [ -z "${{github.event.inputs.cross_compile}}" ]; then
            PREFIX=arm-linux-gnueabihf
          else
            PREFIX=${{github.event.inputs.cross_compile}}
          fi
          echo "::set-output name=PREFIX::${PREFIX}"
          CROSS_COMPILE=${PREFIX}-
          echo "::set-output name=CROSS_COMPILE::${CROSS_COMPILE}"

      - name: Retar Toolchain
        run: tar zcf toolchain.tar.gz toolchain

      - name: Upload Artifact toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain
          path: ./toolchain.tar.gz

  # job_base_rootfs:
  #   name: Base Root File System
  #   needs: [job_toolchain]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Download Artifact toolchain
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: toolchain
  #         path: ./
      
  #     - name: Untar Toolchain
  #       run: tar zxf toolchain.tar.gz

  #     - name: Get Buildroot
  #       run: |
  #         wget https://buildroot.org/downloads/buildroot-2019.02.11.tar.gz
  #         wget https://buildroot.org/downloads/buildroot-2017.02.11.tar.gz
  #         wget https://buildroot.org/downloads/buildroot-2016.02.tar.gz

  #         tar zxf buildroot-2019.02.11.tar.gz
  #         tar zxf buildroot-2017.02.11.tar.gz
  #         tar zxf buildroot-2016.02.tar.gz

  #     - name: Replace Buildroot Package Version
  #       run: |
  #         rm -rf buildroot-2019.02.11/package/openssh
  #         cp -rf buildroot-2016.02/package/openssh buildroot-2019.02.11/package/

  #         rm -rf buildroot-2019.02.11/package/openssl
  #         cp -rf buildroot-2016.02/package/openssl buildroot-2019.02.11/package/

  #         rm -rf buildroot-2019.02.11/package/zlib
  #         cp -rf buildroot-2016.02/package/zlib buildroot-2019.02.11/package/

  #         rm -rf buildroot-2019.02.11/package/mosquitto
  #         cp -rf buildroot-2016.02/package/mosquitto buildroot-2019.02.11/package/

  #         rm -rf buildroot-2019.02.11/package/iproute2
  #         cp -rf buildroot-2017.02.11/package/iproute2 buildroot-2019.02.11/package/

  #         rm -rf buildroot-2019.02.11/package/paho-mqtt-c
  #         cp -rf buildroot-2017.02.11/package/paho-mqtt-c buildroot-2019.02.11/package/

  #     - name: Add Buildroot Package
  #       run: cp -rf htbox-forlinx/buildroot-add/* buildroot-2019.02.11/

  #     - name: Patch Buildroot
  #       run: |
  #         patch -p1 < ../htbox-forlinx/buildroot-patch/ncurses.mk.patch
  #         patch -p1 < ../htbox-forlinx/buildroot-patch/python-ipy_Config.in.patch
  #         patch -p1 < ../htbox-forlinx/buildroot-patch/package_Config.in.patch
  #       working-directory: ./buildroot-2019.02.11

  #     - name: Config Buildroot
  #       run: |
  #         cp -f htbox-forlinx/buildroot-config/config.base.new buildroot-2019.02.11/.config
  #         sed -i "/BR2_TOOLCHAIN_EXTERNAL_PATH/cBR2_TOOLCHAIN_EXTERNAL_PATH=\"${{needs.job_toolchain.outputs.TOOLCHAIN}}\"" buildroot-2019.02.11/.config
  #         sed -i "/BR2_TOOLCHAIN_EXTERNAL_PREFIX/cBR2_TOOLCHAIN_EXTERNAL_PREFIX=\"${{needs.job_toolchain.outputs.PREFIX}}\"" buildroot-2019.02.11/.config
  #         sed -i "/BR2_TOOLCHAIN_EXTERNAL_CUSTOM_PREFIX/cBR2_TOOLCHAIN_EXTERNAL_CUSTOM_PREFIX=\"${{needs.job_toolchain.outputs.PREFIX}}"\" buildroot-2019.02.11/.config
  #         cat buildroot-2019.02.11/.config

  #     - name: Build Buildroot
  #       run: make -j$(nproc)
  #       working-directory: ./buildroot-2019.02.11

  #     - name: Config BusyBox
  #       run: |
  #         cp -f htbox-forlinx/buildroot-config/config.busybox buildroot-2019.02.11/output/build/busybox-1.29.3/.config
  #         rm -f buildroot-2019.02.11/output/build/busybox-1.29.3/.stamp_configured
  #         rm -f buildroot-2019.02.11/output/build/busybox-1.29.3/.stamp_built
  #         rm -f buildroot-2019.02.11/output/build/busybox-1.29.3/.stamp_target_installed

  #     - name: Build Buildroot Again
  #       run: make -j$(nproc)
  #       working-directory: ./buildroot-2019.02.11

  #     - name: Upload Artifact base_rootfs
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: base_rootfs
  #         path: ./buildroot-2019.02.11/output/images/rootfs.tar

  # job_kernel:
  #   name: Kernel
  #   needs: [job_toolchain, job_base_rootfs]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install APT Packages
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y u-boot-tools

  #     - name: Download Artifact toolchain
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: toolchain
  #         path: ./
      
  #     - name: Untar Toolchain
  #       run: tar zxf toolchain.tar.gz

  #     - name: Get Kernel
  #       run: git clone -b 20200803 https://github.com/cookie-dragon/forlinx-335xS-II-kernel.git kernel

  #     - name: Add Kernel File
  #       run: cp -rf htbox-forlinx/kernel-add/* kernel/

  #     - name: Patch Kernel
  #       run : patch -p1 < ../common/kernel-patch/timeconst.pl.x64.patch
  #       working-directory: ./kernel

  #     - name: Build Kernel
  #       env:
  #         TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
  #         CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
  #       run: |
  #         export PATH=${TOOLCHAIN}/bin:$PATH
  #         make distclean ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
  #         make ok335xhtbox_evm_linux_defconfig ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
  #         make -j$(nproc) ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
  #         make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE uImage
  #         make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules
  #       working-directory: ./kernel

  #     - name: Upload Artifact uImage
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: uImage
  #         path: ./kernel/arch/arm/boot/uImage

  #     - name: Download Artifact base_rootfs
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: base_rootfs
  #         path: ./

  #     - name: Untar Base Root File System
  #       run: |
  #         mkdir -p rootfs
  #         sudo tar xf rootfs.tar -C ./rootfs/
          
  #     - name: Kernel Modules Install
  #       env:
  #         CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
  #       run: sudo make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules_install INSTALL_MOD_PATH=../rootfs/
  #       working-directory: ./kernel

  #     - name: Tar Base Root File System With Modules
  #       run: |
  #         tree -pugL 1 rootfs
  #         sudo tar zcf rootfs.tar.gz rootfs/

  #     - name: Upload Artifact base_rootfs_with_modules
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: base_rootfs_with_modules
  #         path: ./rootfs.tar.gz

  job_cc_stress:
    name: Job - stress
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:
    
      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./
      
      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz

      - name: Get
        run: |
          wget https://fossies.org/linux/privat/stress-1.0.4.tar.gz
          tar zxf stress-1.0.4.tar.gz
         
      - name: Build
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          ./configure CC=${CROSS_COMPILE}gcc --host=$CROSS_COMPILE
          make
        working-directory: ./stress-1.0.4

      - name: Tar
        run: |
          sudo mkdir -p rootfs/usr/local/bin
          sudo cp -rf stress-1.0.4/src/stress rootfs/usr/local/bin
          tree -pug rootfs
          sudo tar zcf rootfs-stress.tgz rootfs/

      - name: Upload Artifact stress
        uses: actions/upload-artifact@v2
        with:
          name: stress
          path: ./rootfs-stress.tgz

  job_cc_rt-tests:
    name: Job - rt-tests
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:
    
      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./
      
      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz
        
      - name: Get
        run: |
          git clone git://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git
          cd rt-tests
          git checkout stable/v1.0

      - name: Fix
        run: |
          sed -i '2c CC=${CROSS_COMPILE}gcc' Makefile
          sed -i '3c AR=${CROSS_COMPILE}ar' Makefile
          cat Makefile
        working-directory: ./rt-tests
        
      - name: Build
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make
        working-directory: ./rt-tests

      - name: Tar
        run: |
          sudo mkdir -p rootfs/usr/local/bin
          sudo cp -rf rt-tests/cyclictest rootfs/usr/local/bin
          tree -pug rootfs
          sudo tar zcf rootfs-rt-tests.tgz rootfs/

      - name: Upload Artifact rt-tests
        uses: actions/upload-artifact@v2
        with:
          name: rt-tests
          path: ./rootfs-rt-tests.tgz

  job_cc_wireless:
    name: Job - wireless
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:

      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./
      
      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz
        
      - name: Git RTL8723D
        run: git clone -b v5.2.15.1_26226.20180129_COEX20171212-2222 https://github.com/cookie-dragon/realtek-rtl8723d.git 

      - name: Untar WirelessTools
        run: |
          tar zxf wireless_tools.30.rtl.tar.gz
        working-directory: ./realtek-rtl8723d/wireless_tools

      - name: Fix WirelessTools
        run: |
          sed -i "8c PREFIX = ./usr/local" Makefile
          sed -i "12c CC = ${{needs.job_toolchain.outputs.CROSS_COMPILE}}gcc" Makefile
          sed -i "14c AR = ${{needs.job_toolchain.outputs.CROSS_COMPILE}}ar" Makefile
          sed -i "15c RANLIB = ${{needs.job_toolchain.outputs.CROSS_COMPILE}}ranlib" Makefile
          cat Makefile
        working-directory: ./realtek-rtl8723d/wireless_tools/wireless_tools.30.rtl

      - name: Build WirelessTools
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make
          sudo make install
        working-directory: ./realtek-rtl8723d/wireless_tools/wireless_tools.30.rtl

      - name: Untar WpaSupplicant And Hostapd
        run: |
          tar zxf wpa_supplicant_hostapd-0.8_rtw_r24647.20171025.tar.gz
        working-directory: ./realtek-rtl8723d/wpa_supplicant_hostapd

      - name: Build Hostapd
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make CC=${CROSS_COMPILE}gcc
          sudo make install
        working-directory: ./realtek-rtl8723d/wpa_supplicant_hostapd/wpa_supplicant_hostapd-0.8_rtw_r24647.20171025/hostapd

      - name: Build WpaSupplicant
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make CC=${CROSS_COMPILE}gcc
          sudo make install
        working-directory: ./realtek-rtl8723d/wpa_supplicant_hostapd/wpa_supplicant_hostapd-0.8_rtw_r24647.20171025/wpa_supplicant

      - name: Tar
        run: |
          sudo mkdir -p rootfs
          sudo cp -rf realtek-rtl8723d/wireless_tools/wireless_tools.30.rtl/usr rootfs
          sudo mkdir -p rootfs/usr/local/bin
          sudo cp -rf /usr/local/bin/hostapd rootfs/usr/local/bin
          sudo cp -rf /usr/local/bin/hostapd_cli rootfs/usr/local/bin
          sudo mkdir -p rootfs/usr/local/sbin
          sudo cp -rf /usr/local/sbin/wpa_cli rootfs/usr/local/sbin
          sudo cp -rf /usr/local/sbin/wpa_passphrase rootfs/usr/local/sbin
          sudo cp -rf /usr/local/sbin/wpa_supplicant rootfs/usr/local/sbin
          tree -pug rootfs
          sudo tar zcf rootfs-wireless.tgz rootfs/

      - name: Upload Artifact wireless
        uses: actions/upload-artifact@v2
        with:
          name: wireless
          path: ./rootfs-wireless.tgz

  job_cc_snap7:
    name: Job - snap7
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:

      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./
      
      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz
        
      - name: Get
        run: |
          wget https://netix.dl.sourceforge.net/project/snap7/Snap7-IoT/snap7-iot-arm/snap7-iot-arm-1.4.2.tar.gz
          tar zxvf snap7-iot-arm-1.4.2.tar.gz

      - name: Fix
        run: |
          sed -i '8c LinkerName := ${CROSS_COMPILE}g++' common.mk
          sed -i '9c SharedObjectLinkerName := ${CROSS_COMPILE}g++ -shared -fPIC' common.mk
          sed -i '30c AR := ${CROSS_COMPILE}ar rcus' common.mk
          sed -i '31c CXX := ${CROSS_COMPILE}g++' common.mk
          sed -i '32c CC := ${CROSS_COMPILE}gcc' common.mk
          cat common.mk
        working-directory: ./snap7-iot-arm-1.4.2/build/unix

      - name: Build
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make -f arm_v7_linux.mk
          sudo cp -f ../bin/arm_v7-linux/libsnap7.so /usr/lib
        working-directory: ./snap7-iot-arm-1.4.2/build/unix

      - name: Tar
        run: |
          sudo mkdir -p rootfs/usr/lib
          sudo cp -rf /usr/lib/libsnap7.so rootfs/usr/lib
          tree -pug rootfs
          sudo tar zcf rootfs-snap7.tgz rootfs/

      - name: Upload Artifact snap7
        uses: actions/upload-artifact@v2
        with:
          name: snap7
          path: ./rootfs-snap7.tgz

  job_rootfs_part_cc:
    name: Job - Rootfs Part - Cross Compile
    needs: [job_cc_stress, job_cc_rt-tests, job_cc_wireless, job_cc_snap7]
    runs-on: ubuntu-18.04
    steps:
      - name: Download Artifact stress
        uses: actions/download-artifact@v2
        with:
          name: stress
          path: ./

      - name: Untar stress
        run: sudo tar zxf rootfs-stress.tgz

      - name: Download Artifact rt-tests
        uses: actions/download-artifact@v2
        with:
          name: rt-tests
          path: ./ 

      - name: Untar rt-tests
        run: sudo tar zxf rootfs-rt-tests.tgz

      - name: Download Artifact wireless
        uses: actions/download-artifact@v2
        with:
          name: wireless
          path: ./

      - name: Untar wireless
        run: sudo tar zxf rootfs-wireless.tgz

      - name: Download Artifact snap7
        uses: actions/download-artifact@v2
        with:
          name: snap7
          path: ./

      - name: Untar snap7
        run: sudo tar zxf rootfs-snap7.tgz

      - name: Fix
        run: tree -pug rootfs

      - name: Tar
        run: sudo tar zcf rootfs_part_cc.tgz rootfs/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_part_cc
          path: ./rootfs_part_cc.tgz

  job_rootfs_part_base:
    name: Job - Rootfs Part - Base
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Rootfs Dir
        run: |
          mkdir -p rootfs
          sudo cp -rf htbox-forlinx/rootfs-base-add/* rootfs/
          sudo chown -R root:root rootfs

      - name: Fix
        run: |
          sudo find . -type d | xargs sudo chmod 755
          sudo find . -type f | xargs sudo chmod 644

          sudo chmod -f +x etc/mdev/*

          tree -pug rootfs
        working-directory: ./rootfs

      - name: Tar
        run: sudo tar zcf rootfs_part_base.tgz rootfs/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_part_base
          path: ./rootfs_part_base.tgz

  job_rootfs_part_advance:
    name: Job - Rootfs Part - Advance
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Rootfs Dir
        run: |
          sudo mkdir -p rootfs
          # sudo cp -rf htbox-forlinx/rootfs-advance-add/* rootfs/
          sudo chown -R root:root rootfs

      - name: Fix
        run: |
          sudo find . -type d | xargs sudo chmod 755
          sudo find . -type f | xargs sudo chmod 644

          tree -pug rootfs
        working-directory: ./rootfs

      - name: Tar
        run: sudo tar zcf rootfs_part_advance.tgz rootfs/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_part_advance
          path: ./rootfs_part_advance.tgz

  job_rootfs_part_custom:
    name: Job - Rootfs Part - Custom
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Rootfs Dir
        run: |
          sudo mkdir -p rootfs
          sudo cp -rf htbox-forlinx/rootfs-custom-add/* rootfs/
          sudo chown -R root:root rootfs

      - name: Fix
        run: |
          sudo find . -type d | xargs sudo chmod 750
          sudo find . -type f | xargs sudo chmod 640

          sudo chmod -f +x usr/local/bin/*
          sudo chmod -f +x opt/sbin/*

          sudo chmod -f +x etc/init.d/*

          sudo chmod -f 600 etc/cron/crontabs/*

          tree -pug rootfs
        working-directory: ./rootfs

      - name: Tar
        run: sudo tar zcf rootfs_part_custom.tgz rootfs/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_part_custom
          path: ./rootfs_part_custom.tgz

  job_rootfs_part_business:
    name: Job - Rootfs Part - Business
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Rootfs Dir
        run: |
          sudo mkdir -p rootfs
          sudo cp -rf htbox-forlinx/rootfs-business-add/* rootfs/
          sudo chown -R root:root rootfs

      - name: Fix
        run: |
          sudo find . -type d | xargs sudo chmod 750
          sudo find . -type f | xargs sudo chmod 640

          sudo chmod -f +x opt/bin/*

          sudo chmod -f +x etc/init.d/*

          tree -pug rootfs
        working-directory: ./rootfs

      - name: Tar
        run: sudo tar zcf rootfs_part_business.tgz rootfs/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_part_business
          path: ./rootfs_part_business.tgz

#   job_final_rootfs:
#     name: Final Root File System
#     needs: [job_kernel, job_rootfs_part_cc, job_rootfs_part_base, job_rootfs_part_advance, job_rootfs_part_custom, job_rootfs_part_business]
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install APT Packages
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y mtd-utils

#       - name: Download Artifact base_rootfs_with_modules
#         uses: actions/download-artifact@v2
#         with:
#           name: base_rootfs_with_modules
#           path: ./

#       - name: Untar Root File System
#         run: sudo tar zxf rootfs.tar.gz

#       - name: Check
#         run: tree -pugL 2 rootfs

# # ########## # ########## # ########## # ########## # ########## #

#       - name: Fix Root File System (Base)
#         run: |
#           sudo rm -rf rootfs/lib/modules/*/build
#           sudo rm -rf rootfs/lib/modules/*/source

#       - name: Download Artifact rootfs_part_base
#         uses: actions/download-artifact@v2
#         with:
#           name: rootfs_part_base
#           path: ./

#       - name: Patch Root File System (Base)
#         run: |
#           sudo patch -p1 < ../htbox-forlinx/rootfs-patch/etc_mdev.conf.patch
#           sudo patch -p1 < ../htbox-forlinx/rootfs-patch/etc_profile.patch
#         working-directory: ./rootfs

# # ########## # ########## # ########## # ########## # ########## #

#       # - name: Download Artifact rootfs_part_cc
#       #   uses: actions/download-artifact@v2
#       #   with:
#       #     name: rootfs_part_cc
#       #     path: ./

#       # - name: Download Artifact rootfs_part_advance
#       #   uses: actions/download-artifact@v2
#       #   with:
#       #     name: rootfs_part_advance
#       #     path: ./

#       # - name: Patch Root File System (Advance)
#       #   run: |
#       #     sudo patch -p1 < ../htbox-forlinx/rootfs-patch/etc_bluetooth_main.conf.patch
#       #   working-directory: ./rootfs

# # ########## # ########## # ########## # ########## # ########## #

#       # - name: Download Artifact rootfs_part_custom
#       #   uses: actions/download-artifact@v2
#       #   with:
#       #     name: rootfs_part_custom
#       #     path: ./

#       # - name: Patch Root File System (Custom)
#       #   run: |
#       #     sudo patch -p1 < ../htbox-forlinx/rootfs-patch/etc_inittab.patch
#       #   working-directory: ./rootfs

# # ########## # ########## # ########## # ########## # ########## #

#       # - name: Fix Root File System (Business)
#       #   run: |
#       #     sudo rm -rf rootfs/etc/init.d/S60openvpn

#       # - name: Download Artifact rootfs_part_business
#       #   uses: actions/download-artifact@v2
#       #   with:
#       #     name: rootfs_part_business
#       #     path: ./

# # ########## # ########## # ########## # ########## # ########## #

#       - name: Tar Final Root File System
#         run: sudo tar zcf rootfs.tar.gz rootfs/

#       - name: Upload Artifact final_rootfs
#         uses: actions/upload-artifact@v2
#         with:
#           name: final_rootfs
#           path: ./rootfs.tar.gz

#       - name: Build UBI File System
#         run: |
#           sudo mkfs.ubifs -F -r rootfs -m 2048 -e 126976 -c 1866 -o ubifs.img
#           sudo ubinize -o ubi.img -m 2048 -p 128KiB -s 2048 -O 2048 htbox-forlinx/rootfs-config/ubinize-256M.cfg

#       - name: Upload Artifact ubi.img
#         uses: actions/upload-artifact@v2
#         with:
#           name: ubi.img
#           path: ./ubi.img

