name: HTBOX-via-hzmct CI

on:
  push:
    branches:
      - main
    paths: 
      - 'HTBOX-via-hzmct/version.json'
  workflow_dispatch:
    inputs:
      cross_compile:
        description: 'PREFIX'
        required: true
        default: 'arm-linux-gnueabihf'

env:
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: false

jobs:

  job_env:
    name: ENV
    runs-on: ubuntu-18.04
    outputs:
      KERNEL_VERSION: ${{steps.step_set_version.outputs.KERNEL_VERSION}}
      KERNEL_SUBVERSION: ${{steps.step_set_version.outputs.KERNEL_SUBVERSION}}
      FILE_SYS_VERSION: ${{steps.step_set_version.outputs.FILE_SYS_VERSION}}
      DATE_VERSION: ${{steps.step_set_version.outputs.DATE_VERSION}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: step_set_version
        name: Set Version
        run: |
          KERNEL_VERSION=`cat HTBOX-via-hzmct/version.json | jq -r '.kernel_version'`
          KERNEL_SUBVERSION=`cat HTBOX-via-hzmct/version.json | jq -r '.kernel_subversion'`
          FILE_SYS_VERSION=`cat HTBOX-via-hzmct/version.json | jq -r '.file_sys_version'`
          DATE_VERSION=`cat HTBOX-via-hzmct/version.json | jq -r '.date_version'`
          
          echo ${KERNEL_VERSION} ${KERNEL_SUBVERSION} ${FILE_SYS_VERSION} ${DATE_VERSION}

          echo "::set-output name=KERNEL_VERSION::${KERNEL_VERSION}"
          echo "::set-output name=KERNEL_SUBVERSION::${KERNEL_SUBVERSION}"
          echo "::set-output name=FILE_SYS_VERSION::${FILE_SYS_VERSION}"
          echo "::set-output name=DATE_VERSION::${DATE_VERSION}"

  job_toolchain:
    name: Toolchain
    runs-on: ubuntu-18.04
    outputs:
      TOOLCHAIN: ${{steps.step_set_toolchain.outputs.TOOLCHAIN}}
      PREFIX: ${{steps.step_set_prefix_cross_compile.outputs.PREFIX}}
      CROSS_COMPILE: ${{steps.step_set_prefix_cross_compile.outputs.CROSS_COMPILE}}
    steps:
      
      - name: Wget Toolchain
        run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Untar Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
      
      - name: Rename Toolchain
        run: mv gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux toolchain
        
      - id: step_set_toolchain
        name: Set TOOLCHAIN
        run: |
          TOOLCHAIN=`pwd`
          echo "::set-output name=TOOLCHAIN::${TOOLCHAIN}"
        working-directory: ./toolchain
        
      - id: step_set_prefix_cross_compile
        name: Set PREFIX and CROSS_COMPILE
        run: |
          if [ -z "${{github.event.inputs.cross_compile}}" ]; then
            PREFIX=arm-linux-gnueabihf
          else
            PREFIX=${{github.event.inputs.cross_compile}}
          fi
          echo "::set-output name=PREFIX::${PREFIX}"
          CROSS_COMPILE=${PREFIX}-
          echo "::set-output name=CROSS_COMPILE::${CROSS_COMPILE}"

      - name: Retar Toolchain
        run: tar zcf toolchain.tar.gz toolchain

      - name: Upload Artifact toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain
          path: ./toolchain.tar.gz

  job_rootfs_hzmct:
    name: Hzmct Root File System
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Official Root File System
        run: git clone -b 201710 https://github.com/cookie-dragon/hzmct-IOT-BOX-V6-rootfs.git

      - name: Untar Official Root File System
        run: |
          sudo tar zxf hzmct-IOT-BOX-V6-rootfs/IOT-BOX-V6-rootfs.tar.gz

      - name: Fix Root File System
        run: |
          sudo rm -rf rootfs/rootfs/etc/rc5.d/S20boa
          sudo rm -rf rootfs/rootfs/etc/init.d/boa
          sudo rm -rf rootfs/rootfs/etc/boa
          sudo rm -rf rootfs/rootfs/etc/mime.types
          sudo rm -rf rootfs/rootfs/usr/sbin/boa
          sudo rm -rf rootfs/rootfs/usr/sbin/boa_indexer
          sudo rm -rf rootfs/rootfs/usr/httproot
          sudo rm -rf rootfs/rootfs/var/boa

          sudo rm -rf rootfs/rootfs/etc/rc5.d/S99sztenv
          sudo rm -rf rootfs/rootfs/etc/init.d/sztenv
          sudo rm -rf rootfs/rootfs/etc/quectel-CM
          sudo rm -rf rootfs/rootfs/etc/yiyuan_4g

          sudo rm -rf rootfs/rootfs/usr/sbin/sqlite3
          sudo rm -rf rootfs/rootfs/lib/libsqlite3*
          sudo rm -rf rootfs/rootfs/lib/libcrypto*
          sudo rm -rf rootfs/rootfs/usr/lib/libssl*
          sudo rm -rf rootfs/rootfs/usr/bin/curl
          sudo rm -rf rootfs/rootfs/usr/lib/libcurl*
          sudo rm -rf rootfs/rootfs/usr/lib/libz*

          sudo chmod 666 rootfs/rootfs/etc/group
          sudo echo "sshd:*:74:" >> rootfs/rootfs/etc/group
          sudo echo "htuser:x:1000:" >> rootfs/rootfs/etc/group
          sudo chmod 644 rootfs/rootfs/etc/group

          sudo chmod 666 rootfs/rootfs/etc/gshadow
          sudo echo "htuser:!::" >> rootfs/rootfs/etc/gshadow
          sudo chmod 400 rootfs/rootfs/etc/gshadow

          sudo chmod 666 rootfs/rootfs/etc/passwd
          sudo sed -i "1c root:5vQYoRI7nPbz2:0:0:root:/home/root:/bin/sh" rootfs/rootfs/etc/passwd
          sudo echo "sshd:*:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin" >> rootfs/rootfs/etc/passwd
          sudo echo "htuser:x:1000:1000::/home/htuser:/bin/sh" >> rootfs/rootfs/etc/passwd
          sudo chmod 644 rootfs/rootfs/etc/passwd

          sudo chmod 666 rootfs/rootfs/etc/shadow
          echo "htuser:jW.GgY9ZZlPaA:18696:0:99999:7:::" >> rootfs/rootfs/etc/shadow
          sudo chmod 400 rootfs/rootfs/etc/shadow

          sudo sed -i "32c usr:2345:respawn:/bin/login -f htuser" rootfs/rootfs/etc/inittab

          sudo chmod u+s rootfs/rootfs/usr/bin/su
          sudo mkdir -p rootfs/rootfs/home/htuser

      - name: Tar Base Root File System
        run: sudo tar cf rootfs.tar * 
        working-directory: ./rootfs/rootfs

      - name: Upload Artifact rootfs_hzmct
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_hzmct
          path: ./rootfs/rootfs/rootfs.tar

  job_uboot:
    name: Uboot
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:

      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./

      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz

      - name: Get Uboot
        run: git clone -b 20171011 https://github.com/cookie-dragon/hzmct-IOT-BOX-V6-uboot.git uboot

      - name: Build Uboot
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          touch .scmversion
          make distclean CROSS_COMPILE=$CROSS_COMPILE
          make -j$(nproc) O=am335 CROSS_COMPILE=$CROSS_COMPILE am335x_evm
        working-directory: ./uboot

      - name: Upload Artifact MLO_u-boot
        uses: actions/upload-artifact@v2
        with:
          name: MLO_u-boot
          path: |
            ./uboot/am335/MLO
            ./uboot/am335/u-boot.img

  job_kernel:
    name: Kernel
    needs: [job_toolchain, job_rootfs_hzmct]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install APT Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y u-boot-tools

      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./

      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz

      - name: Get Kernel
        run: git clone -b 20171101 https://github.com/cookie-dragon/hzmct-IOT-BOX-V6-kernel.git kernel

      - name: Add Kernel File
        run: cp -rf HTBOX-via-hzmct/kernel-add/* kernel/

      - name: Config Kernel
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          touch .scmversion
          make distclean ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make am335x_hzmct_defconfig ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
        working-directory: ./kernel

      - name: Patch Kernel
        run : |
          patch -p1 < ../common/kernel-patch/timeconst.pl.x64.patch
          patch -p1 < ../HTBOX-via-hzmct/kernel-patch/diff.patch
        working-directory: ./kernel

      - name: Build Kernel
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: |
          export PATH=${TOOLCHAIN}/bin:$PATH
          make -j$(nproc) ARCH=arm CROSS_COMPILE=$CROSS_COMPILE
          make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE uImage
          make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules
        working-directory: ./kernel

      - name: Upload Artifact uImage
        uses: actions/upload-artifact@v2
        with:
          name: uImage
          path: ./kernel/arch/arm/boot/uImage

      - name: Download Artifact rootfs_hzmct
        uses: actions/download-artifact@v2
        with:
          name: rootfs_hzmct
          path: ./

      - name: Untar Buildroot Root File System
        run: |
          mkdir -p rootfs
          sudo tar xf rootfs.tar -C ./rootfs/
          
      - name: Kernel Modules Install
        env:
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        run: sudo make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE modules_install INSTALL_MOD_PATH=../rootfs/
        working-directory: ./kernel

      - name: Tar Buildroot Root File System With Modules
        run: sudo tar zcf rootfs.tar.gz rootfs/

      - name: Upload Artifact rootfs_hzmct_with_modules
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_hzmct_with_modules
          path: ./rootfs.tar.gz

  job_rootfs_part_business:
    name: Job - Rootfs Part - Business
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Rootfs Dir
        run: |
          sudo mkdir -p rootfs
          sudo cp -rf HTBOX-via-hzmct/rootfs-add/* rootfs/
          sudo cp -rf rootfs/home/WebOnBoard/shell/pyconfig.sh rootfs/etc/init.d/
          sudo cp -rf rootfs/home/WebOnBoard/shell/pynet.sh rootfs/etc/init.d/
          sudo chown -R root:root rootfs

      - name: Fix
        run: |
          sudo mkdir -p etc/rc5.d
          sudo mkdir -p media/card

          sudo find . -type d | xargs sudo chmod 755
          sudo find . \( -path ./usr/lib/python3.6 -o -path ./usr/lib/python2.7 \) -prune -o -type f | xargs sudo chmod 644

          sudo chmod 755 etc/init.d/*
          sudo chmod 755 etc/quectel-CM
          sudo chmod 755 usr/bin/*

          sudo chmod 750 ./home/WebOnBoard
          sudo find ./home/WebOnBoard -type d | xargs sudo chmod 750
          sudo find ./home/WebOnBoard -type f | xargs sudo chmod 640
          sudo chmod 750 ./home/WebOnBoard/auto_start.sh
          sudo chmod 750 ./home/WebOnBoard/autorun.sh
          sudo chmod 750 ./home/WebOnBoard/HtBoxMain
          sudo chmod 750 ./home/WebOnBoard/main_opc.py
          sudo chmod 750 ./home/WebOnBoard/openvpn.sh
          sudo chmod 750 ./home/WebOnBoard/setup.sh
          sudo chmod 750 ./home/WebOnBoard/static_config2.py
          sudo chmod 750 ./home/WebOnBoard/static_monitor.py
          sudo chmod 750 ./home/WebOnBoard/static_start2.py

        working-directory: ./rootfs

      - name: Untar Package
        run: |
          sudo mkdir -p rootfs/usr

          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/openssl-1.0.2s.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/zlib-1.2.11.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/curl-7.65.1.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/sqlite-3.28.tar.gz -C rootfs/usr/

          sudo mkdir -p rootfs/usr/local
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/openssh-8.0p1.tar.gz -C rootfs/usr/local/
          sudo mkdir -p rootfs/var/run
          sudo mkdir -p rootfs/var/empty

          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/openvpn-2.3.18.tar.gz -C rootfs/usr/

          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/jq-1.5.tar.gz -C /usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/bridge-utils-1.5.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/ntp-4.2.8p13.tar.gz -C rootfs/usr/

          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/bzip2-1.0.6.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/gdbm-1.18.1.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/readline-8.0.tar.gz -C rootfs/usr/

          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/python-2.7.16.tar.gz -C rootfs/usr/
          sudo rm -rf rootfs/usr/lib/python2.7/test
          sudo find rootfs/usr/lib/python2.7 -name '__pycache__' -type d -exec sudo rm -rf {} \;

          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/python-3.6.9.tar.gz -C rootfs/usr/
          sudo rm -rf rootfs/usr/lib/python3.6/test
          sudo find rootfs/usr/lib/python3.6 -name '__pycache__' -type d -exec sudo rm -rf {} \;

          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/paho.mqtt.c-1.3.1.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/mosquitto-1.4.15-client.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/mosquitto-1.4.15-lib.tar.gz -C rootfs/usr/
          sudo tar zxf HTBOX-via-hzmct/rootfs-untar/mosquitto-1.4.15-src.tar.gz -C rootfs/usr/

      - name: Link Init
        run: |
          sudo ln -s ../init.d/sshd.sh S99sshd.sh
          sudo ln -s ../init.d/mosquitto.sh S99mosquitto.sh
          sudo ln -s ../init.d/sztenv S99sztenv
          sudo ln -s ../init.d/pynet.sh S99pynet.sh
        working-directory: ./rootfs/etc/rc5.d

      - name: Link user lib
        run: |
          sudo ln -s libcjson.so.1.7.12 libcjson.so.1
          sudo ln -s libcjson.so.1 libcjson.so
          sudo ln -s libcjson_utils.so.1.7.12 libcjson_utils.so.1
          sudo ln -s libcjson_utils.so.1 libcjson_utils.so
          sudo ln -s libmodbus.so.5.1.0 libmodbus.so.5
          sudo ln -s libmodbus.so.5 libmodbus.so
          sudo ln -s libstdc++.so.6.0.17 libstdc++.so.6
        working-directory: ./rootfs/usr/lib/

      - name: Link lib
        run: |
          sudo ln -s libcrypto.so.1.0.0 libcrypto.so
        working-directory: ./rootfs/lib/

      - name: Tar
        run: sudo tar zcf rootfs_part_business.tgz rootfs/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_part_business
          path: ./rootfs_part_business.tgz

  job_final_rootfs:
    name: Final Root File System
    needs: [job_kernel, job_rootfs_part_business]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install APT Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y mtd-utils

      - name: Download Artifact rootfs_hzmct_with_modules
        uses: actions/download-artifact@v2
        with:
          name: rootfs_hzmct_with_modules
          path: ./

      - name: Untar Root File System
        run: sudo tar zxf rootfs.tar.gz

      # ########## # ########## # ########## # ########## # ########## #

      - name: Fix Root File System (Base)
        run: |
          sudo rm -rf rootfs/lib/modules/*/build
          sudo rm -rf rootfs/lib/modules/*/source

      - name: Download Artifact rootfs_part_business
        uses: actions/download-artifact@v2
        with:
          name: rootfs_part_business
          path: ./

      - name: Untar rootfs_part_business
        run: sudo tar zxf rootfs_part_business.tgz

      - name: Tar Final Root File System (Business)
        run: sudo tar zcf rootfs_final_business.tar.gz rootfs/

      - name: Upload Artifact rootfs_final_business (Business)
        uses: actions/upload-artifact@v2
        with:
          name: rootfs_final_business
          path: ./rootfs_final_business.tar.gz

      - name: Build UBI File System (Business)
        run: |
          sudo mkfs.ubifs -F -q -r rootfs -m 2048 -e 126976 -c 2047 -o ubifs.img
          sudo ubinize -o ubi.img -m 2048 -p 128KiB HTBOX-via-hzmct/rootfs-config/ubinize.cfg

      - name: Upload Artifact ubi_business (Business)
        uses: actions/upload-artifact@v2
        with:
          name: ubi_business
          path: ./ubi.img

  job_final_package:
    name: Final Package
    needs: [job_env, job_uboot, job_kernel, job_final_rootfs]
    runs-on: ubuntu-18.04
    steps:

      - name: Download Artifact MLO_u-boot
        uses: actions/download-artifact@v2
        with:
          name: MLO_u-boot
          path: ./

      - name: Download Artifact uImage
        uses: actions/download-artifact@v2
        with:
          name: uImage
          path: ./

      - name: Download Artifact ubi_business (Business)
        uses: actions/download-artifact@v2
        with:
          name: ubi_business
          path: ./

      - name: Prepare Dir
        run: |
          mkdir -p output/SD_Flash

      - name: Prepare File
        run: |
          cp MLO output/SD_Flash/
          cp u-boot.img output/SD_Flash/
          cp uImage output/SD_Flash/
          cp ubi.img output/SD_Flash/

      - name: Upload Artifact
        if: ${{ github.ref != 'refs/heads/main'}}
        uses: actions/upload-artifact@v2
        with:
          name: SD_Flash
          path: ./output

      # - name: Organize files
      #   id: organize
      #   if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      #   run: |
      #     zip -qr SD_Flash.zip SD_Flash

      #     echo "FIRMWARE=$PWD/SD_Flash.zip" >> $GITHUB_ENV

      #     RTN_gettoken=`curl --location --request GET "https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=${{ secrets.WECHATWORK_CORPID }}&corpsecret=${{ secrets.WECHATWORK_APP_CORPSECRET }}"`
      #     access_token=`echo ${RTN_gettoken} | jq -r '.access_token'`
      #     echo "ACCESS_TOKEN=${access_token}" >> $GITHUB_ENV

      #     echo "::set-output name=status::success"
      #   working-directory: ./output

      # - name: Upload firmware to outside of Github
      #   id: transfer
      #   if: steps.organize.outputs.status == 'success' && (env.UPLOAD_COWTRANSFER == 'true' || env.UPLOAD_WETRANSFER == 'true') && !cancelled()
      #   run: |
      #     curl -fsSL git.io/file-transfer | sh

      # - name: Upload firmware to Cowtransfer
      #   id: cowtransfer
      #   if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      #   run: |
      #     ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log

      #     L2=`sed -n '2p' cowtransfer.log`
      #     L3=`sed -n '3p' cowtransfer.log`
      #     DownloadLink=${L2#*: }
      #     DownloadCode=${L3#*: }

      #     curl --location --request POST "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${ACCESS_TOKEN}" \
      #     --header 'Content-Type: application/json' \
      #     --data-raw '{
      #       "touser" : "@all",
      #       "msgtype" : "textcard",
      #       "agentid" : '"${{ secrets.WECHATWORK_APP_AGENTID }}"',
      #       "textcard" : {
      #         "title" : "Github Action 生成固件",
      #         "description" : "<div class=\"gray\">'"$(date "+%Y年%m月%d日 %H:%M:%S")"'</div><div class=\"normal\">固件已上传CowTransfer，取件码：'"${DownloadCode}"'</div><div class=\"highlight\">请于24小时内下载</div>",
      #         "url" : "'"${DownloadLink}"'"
      #       }
      #     }'

      # - name: Upload firmware to WeTransfer
      #   id: wetransfer
      #   if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      #   run: |
      #     ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log

      #     L3=`sed -n '3p' wetransfer.log`
      #     DownloadLink=${L3#*: }

      #     curl --location --request POST "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${ACCESS_TOKEN}" \
      #     --header 'Content-Type: application/json' \
      #     --data-raw '{
      #       "touser" : "@all",
      #       "msgtype" : "textcard",
      #       "agentid" : '"${{ secrets.WECHATWORK_APP_AGENTID }}"',
      #       "textcard" : {
      #         "title" : "Github Action 生成固件",
      #         "description" : "<div class=\"gray\">'"$(date "+%Y年%m月%d日 %H:%M:%S")"'</div><div class=\"normal\">固件已上传WeTransfer</div><div class=\"highlight\">请于7日内下载</div>",
      #         "url" : "'"${DownloadLink}"'"
      #       }
      #     }'

      # - name: Create Release
      #   id: create_release
      #   if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{needs.job_env.outputs.DATE_VERSION}}
      #     release_name: Release ${{needs.job_env.outputs.DATE_VERSION}}
      #     draft: false
      #     prerelease: false

      # - name: Upload Release Asset
      #   if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./output/SD_Flash.zip
      #     asset_name: SD_Flash.zip
      #     asset_content_type: application/zip
