name: HTBOX-via-forlinx CI

on:
  push:
    branches:
      - main
    paths: 
      - 'HTBOX-via-forlinx/version.json'
  workflow_dispatch:
    inputs:
      cross_compile:
        description: 'PREFIX'
        required: true
        default: 'arm-linux-gnueabihf'
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:

  job_env:
    name: ENV
    runs-on: ubuntu-18.04
    outputs:
      KERNEL_VERSION: ${{steps.step_set_version.outputs.KERNEL_VERSION}}
      KERNEL_SUBVERSION: ${{steps.step_set_version.outputs.KERNEL_SUBVERSION}}
      FILE_SYS_VERSION: ${{steps.step_set_version.outputs.FILE_SYS_VERSION}}
      DATE_VERSION: ${{steps.step_set_version.outputs.DATE_VERSION}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: step_set_version
        name: Set Version
        run: |
          KERNEL_VERSION=`cat HTBOX-via-forlinx/version.json | jq -r '.kernel_version'`
          KERNEL_SUBVERSION=`cat HTBOX-via-forlinx/version.json | jq -r '.kernel_subversion'`
          FILE_SYS_VERSION=`cat HTBOX-via-forlinx/version.json | jq -r '.file_sys_version'`
          DATE_VERSION=`cat HTBOX-via-forlinx/version.json | jq -r '.date_version'`
          
          echo ${KERNEL_VERSION} ${KERNEL_SUBVERSION} ${FILE_SYS_VERSION} ${DATE_VERSION}

          echo "::set-output name=KERNEL_VERSION::${KERNEL_VERSION}"
          echo "::set-output name=KERNEL_SUBVERSION::${KERNEL_SUBVERSION}"
          echo "::set-output name=FILE_SYS_VERSION::${FILE_SYS_VERSION}"
          echo "::set-output name=DATE_VERSION::${DATE_VERSION}"

  job_toolchain:
    name: Toolchain
    runs-on: ubuntu-18.04
    outputs:
      TOOLCHAIN: ${{steps.step_set_toolchain.outputs.TOOLCHAIN}}
      PREFIX: ${{steps.step_set_prefix_cross_compile.outputs.PREFIX}}
      CROSS_COMPILE: ${{steps.step_set_prefix_cross_compile.outputs.CROSS_COMPILE}}
    steps:
      
      - name: Wget Toolchain
        run: wget https://launchpad.net/linaro-toolchain-binaries/trunk/2013.03/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2

      - name: Untar Toolchain
        run: tar jxf gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux.tar.bz2
      
      - name: Rename Toolchain
        run: mv gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux toolchain
        
      - id: step_set_toolchain
        name: Set TOOLCHAIN
        run: |
          TOOLCHAIN=`pwd`
          echo "::set-output name=TOOLCHAIN::${TOOLCHAIN}"
        working-directory: ./toolchain
        
      - id: step_set_prefix_cross_compile
        name: Set PREFIX and CROSS_COMPILE
        run: |
          if [ -z "${{github.event.inputs.cross_compile}}" ]; then
            PREFIX=arm-linux-gnueabihf
          else
            PREFIX=${{github.event.inputs.cross_compile}}
          fi
          echo "::set-output name=PREFIX::${PREFIX}"
          CROSS_COMPILE=${PREFIX}-
          echo "::set-output name=CROSS_COMPILE::${CROSS_COMPILE}"

      - name: Retar Toolchain
        run: tar zcf toolchain.tar.gz toolchain

      - name: Upload Artifact toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain
          path: ./toolchain.tar.gz

  job_cc_via_python:
    name: Job - CC via Python
    needs: [job_toolchain]
    runs-on: ubuntu-18.04
    steps:

      - name: Download Artifact toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: ./
      
      - name: Untar Toolchain
        run: tar zxf toolchain.tar.gz

      - name: SSH connection to Actions
        env:
          TOOLCHAIN: ${{needs.job_toolchain.outputs.TOOLCHAIN}}
          CROSS_COMPILE: ${{needs.job_toolchain.outputs.CROSS_COMPILE}}
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}





























