name: test CI

on:
  push:
    paths: 
      # - 'common/**'
      # - '.github/workflows/test.yml'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:

  job_toolchain:
    name: Toolchain
    runs-on: ubuntu-18.04
    outputs:
      TOOLCHAIN: ${{steps.step_set_toolchain.outputs.TOOLCHAIN}}
      PREFIX: ${{steps.step_set_prefix_cross_compile.outputs.PREFIX}}
      CROSS_COMPILE: ${{steps.step_set_prefix_cross_compile.outputs.CROSS_COMPILE}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
