name: test CI

on:
  push:
    paths: 
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:

  job_test:
    name: Job - Test
    runs-on: ubuntu-18.04
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Step - Test
      #   run: |
      #     touch a.txt
      #     touch b.txt

      #     mkdir -p rfs_runner/t
      #     cp a.txt rfs_runner/t/
      #     sudo cp b.txt rfs_runner/t/

      #     sudo mkdir -p rfs_root/t
      #     sudo cp b.txt rfs_root/t/

      #     tree -pug

      - name: Step - Test2
        run: |
          mkdir -p rfs_runner
          touch rfs_runner/a.txt
          sudo touch rfs_runner/b.txt
          tar zcf rfs_runner.tgz rfs_runner
          sudo tar zcf rfs_runner2.tgz rfs_runner

          mkdir tmp_runner1
          tar zxf rfs_runner.tgz -C tmp_runner1

          mkdir tmp_runner2
          sudo tar zxf rfs_runner2.tgz -C tmp_runner2

          tree -pug
